### ISSUE TITLE
Using attachments() no attachments are sent if the array contains only one attachment

### ISSUE THREAD

**Issue by yanickv** [nedimf/maildroid#10]
**Describe the bug**
Using attachments() no attachments are sent if the array contains only one attachment

In MaildroidX.kt it checks > 1.

if(attachments != null && attachments!!.isNotEmpty() && attachments!!.size > 1){

**Comment by nedimf** [comment]
You should use `` attachments() `` if there is more then one attachment. 
And if there is only one attachment then you should use `` attachment() ``

**Comment by nedimf** [comment]
If you want to send an array of attachments, you can easily check if the size of the array is greater then 1. If array size is equal **1** just use **``` attachment()```** if array size is **greater** then **1** use **``` attachments() ```**
Good luck :+1:

**Comment by Lars-** [comment]
Why not make it 1 function and handle it after the mail call? It's very unintuitive this way. It took me an hour or so before I went to look for issues on GitHub.
