### ISSUE TITLE
Add failure reason/exception to onFail method of onCompleteCallback

### ISSUE THREAD

**Issue by jamiehiggins** [nedimf/maildroid#12]
Firstly thanks for the library, I've just started using it and it seems to work really well.

What I am lacking though is a way to understand why an email send failed. It would be great if we could get at an underlying exception and/or failure reason in the onFail callback. This is important because if we allow a user to enter SMTP details for their own server and for example they make a typo there is just no way for my app to know or to convey to them why the email send may be failing.

**Comment by nedimf** [comment]
We are trying to make error callback more usefull. Problem relays on Java Mail API how they handle errors. We will try to implement solution to check for same values as original Java Mail API does. 

Thank you for using library :bow:

**Comment by nedimf** [comment]
From latest commit, ``errorMessage`` is present that is showing results from try/catch block. 
@jamiehiggins  have look and let me know if this what you have asked for.

**Comment by jamiehiggins** [comment]
Many thanks for this, it looks perfect for my needs

**Comment by nedimf** [comment]
Great, have fun :smile:
