### ISSUE TITLE
No onFail callback for an invalid SMTP server address or port

### ISSUE THREAD

**Issue by jamiehiggins** [nedimf/maildroid#13]
If I attempt to send an email to an invalid SMTP server address or port, I never see the onCompleteCallback being called.

**To Reproduce**
1. Configure a MaildroidX builder with an invalid SMTP address (e.g. dummy.smtp.com) and all other details correct.
2. Call mail() to attempt to send the email

**Expected behavior**
onFail() should be called with an appropriate errorString

**Comment by nedimf** [comment]
Increase timeout to more then 5 seconds. Java Mail API takes time to identify connection problem.

**Comment by jamiehiggins** [comment]
I have been using a 7 second timeout. I will try with higher values.

**Comment by nedimf** [comment]
If you need more help be free to add me on Gitter https://gitter.im/maildroid/community

**Comment by nedimf** [comment]
Can you provide information if that ``timeout`` increase worked?
