### ISSUE TITLE
smtpAuthentication value cannot be false

### ISSUE THREAD

**Issue by jamiehiggins** [nedimf/maildroid#15]
The builder allows us to pass a boolean value through for smtpAuthentication but in reality we cannot pass false, because an IllegalArgumentException is thrown.

**To Reproduce**
Create a MaildroidX.Builder with smtpAuthentication(false) and try to send an email

**Expected behavior**
We should be allowed to pass a value of false. If this is not something that can be configured then it should be removed from the builder.

Here is the code that means we can never pass a false value:

if(!smtpAuthentication) throw IllegalArgumentException("MaildroidX detected that you didn't pass [smtpAuthentication] value to the builder!")

**Comment by nedimf** [comment]
Oh,I will fix it as soon as possible.Thank you :pray:
