### ISSUE TITLE
Cannot send via yahoo or Google SMTP servers

### ISSUE THREAD

**Issue by jamiehiggins** [nedimf/maildroid#17]
When I configure the library to user SMTP server from Yahoo or Google, the sending fails.

I am using Yahoo configuration settings from here: https://help.yahoo.com/kb/SLN4724.html

When using port 465 I get the following error:
Failed to send email to: abc@xyz.com: javax.mail.AuthenticationFailedException: 535 5.7.0 (#AUTH005) Too many bad auth attempts..

When using port 587 I get the following error:
Failed to send email to: abc@xyz.com: com.sun.mail.smtp.SMTPSendFailedException: 450 Requested mail action not taken: mailbox unavailable.

**Comment by jamiehiggins** [comment]
Apologies this is not an issue with the library but an extra security step by Yahoo. I needed to setup an app password and then I was able to send via the library.

https://help.yahoo.com/kb/SLN15241.html

The same is true for Gmail and I was able to send via the gmail smtp server as well.

**Comment by nedimf** [comment]
No worries ,I see you have been using this library a lot,so if you are building app that you will publish later I would like to put your app in show case section of the library. Keep it up :facepunch:

**Comment by jamiehiggins** [comment]
The app is already live and has existed for years. I'm happy for you to add it to the showcase section: https://play.google.com/store/apps/details?id=com.arlosoft.macrodroid

**Comment by nedimf** [comment]
Thank you very much,I ll add it as soon as possible :pray:

**Comment by nedimf** [comment]
Damn,I just saw number of downloads on your app and I have download that app too.Congratulations man I am really glad such app uses this library. :tada:

**Comment by jamiehiggins** [comment]
Well thanks to you I finally got around to adding the STMP email feature. This is only a spare time side project (albeit one that has spanned many years) so I always put off adding SMTP support because it seemed too much effort with no simple libraries until now!

**Comment by nedimf** [comment]
You can't even imagine how happy I am this helped someone to solve real issue.You have boosted my confidance a lot by telling me this :bow: .Sorry for my not that frequent response I go to high school so I can't be always first to response :)

**Comment by deepalitech9** [comment]
What could be the app name if we are sending it through automation script?

**Comment by nedimf** [comment]
@deepalitech9 can you elaborate on your question more? What are you trying to achieve?
