### ISSUE TITLE
Enumeration for email type

### ISSUE THREAD

**Issue by igormatyushkin014** [nedimf/maildroid#2]
Would be great if you make enumeration for email type (HTML, PLAIN) instead of string.

**Comment by nedimf** [comment]
I will :), thank you for your support

**Comment by nedimf** [comment]
I have added enumeration with today's push. 
Now email types are declared with
```kotlin
type.(MaildroidXType.HTML)
```
or 
```kotlin
type.(MaildroidXType.PLAIN)
```

as stated in the updated documentation
