### ISSUE TITLE
What license is your library operating under?

### ISSUE THREAD

**Issue by KatieBarnett** [nedimf/maildroid#22]
**Is your feature request related to a problem? Please describe.**
I'm keen to use your library - looks great!
I just need to know what open source license it uses (if any) so I can decide whether to use it in my app.

**Additional context**
You can get some info here: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by nedimf** [comment]
Hey @KatieBarnett . I'm glad you would like to use this library. This library is operating under MIT license.
