### ISSUE TITLE
Failed to resolve: com.github.nedimf:maildroid:v0.0.4

### ISSUE THREAD

**Issue by Jeluchu** [nedimf/maildroid#23]
Hello!
I went to update to v0.0.4 but I get this error, however v0.0.3 works correctly and without any problems, is the new version enabled for the Gradle?

```
ERROR: Failed to resolve: com.github.nedimf:maildroid:v0.0.4
Show in Project Structure dialog
Affected Modules: app
```

The application is programmed in Kotlin for Android and the Android Studio version is as follows:

**Android Studio 3.6.3**
Build #AI-192.7142.36.36.6392135, built on April 14, 2020
Runtime version: 1.8.0_212-release-1586-b04 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4012M
Cores: 12
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: org.jetbrains.kotlin, com.google.services.firebase, wu.seal.tool.jsontokotlin

**Comment by nedimf** [comment]
So sorry, to hear that you had issue with a gradle, let me see what I can do. 
Thank you for opening this issue and brining it to my intention.

**Comment by Jeluchu** [comment]
No problem, if you need more information you can ask me without problem, I am waiting for news

**Comment by nedimf** [comment]
@Jeluchu I'm looking at the problem now.

**Comment by Jeluchu** [comment]
Cool, it's been fast!

**Comment by nedimf** [comment]
Ok, so problem is not in library, I have opened new project and test it and I saw there is problem. I went trough documentation and saw that I forgot to add 
```maven { url 'https://jitpack.io' }```
Into my build root.gradle file so I have added it and that saved problem. I think you had the same issue. Try adding 
```
	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```
and then sync and see what happens that should solve your issue.

**Comment by nedimf** [comment]
Although on second thought, I'm not sure how v0.0.3 is working?

**Comment by Jeluchu** [comment]
@nedimf I am currently using v0.0.3 and it works perfectly, about what you tell me about adding:
`maven { url 'https://jitpack.io' }`

I have it added, it is more this is all I have in that section:

```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://maven.google.com" }
        maven { url 'https://jitpack.io' }
    }
}
```

I changed the version number of the library to  v0.0.4, and I got the error that I showed you at the beginning of the thread

**Comment by nedimf** [comment]
Oh, ok please add it before ```maven.google.com``` and let me know :)

**Comment by Jeluchu** [comment]
I just made the change that you have asked me, but it shows me the same error

```
ERROR: Failed to resolve: com.github.nedimf:maildroid:v0.0.4
Show in Project Structure dialog
Affected Modules: app
```
At first it seems that it starts to download the new library version and then it jumps this error as if that version did not exist

**Comment by nedimf** [comment]
Can you remove ```        maven { url "https://maven.google.com" } ``` and try again. @Jeluchu

**Comment by Jeluchu** [comment]
The same problem

```
ERROR: Failed to resolve: com.github.nedimf:maildroid:v0.0.4
Show in Project Structure dialog
Affected Modules: app
```

**Comment by nedimf** [comment]
Can you show me how you are implementing in build.gradle @Jeluchu

**Comment by nedimf** [comment]
https://stackoverflow.com/a/50389289/11555781
Try removing maven { url "https://maven.google.com" } in fully

**Comment by Jeluchu** [comment]
The library is implemented as follows:
`implementation 'com.github.nedimf:maildroid:v0.0.4'`

Previously it was:
`implementation 'com.github.nedimf:maildroid:v0.0.3'`

I have tried what you have sent me from the maven and that is still not the problem, since it shows me the same problem that I have mentioned before

```
ERROR: Failed to resolve: com.github.nedimf:maildroid:v0.0.4
Show in Project Structure dialog
Affected Modules: app

```

**Comment by Jeluchu** [comment]
I just noticed that in your readme on the JitPack version card, v0.0.3 still comes out, I do not know if you have uploaded the version, since Android Studio does not recognize that there is a new version either (when there are new versions it underlines you the implementation)

<h1 align="center">
  <br>
  <a href="http://www.nedim.co"><img src="https://raw.githubusercontent.com/nedimf/maildroid/master/maildroid.png" alt="nedim.co" width="200"></a>
  <br>
  Maildroid
  <br>
</h1>
<h4 align="center"> :tada: Maildroid is a small robust android library for sending emails using SMTP server :tada:</h4>
<p align = "center">
<a href="https://android-arsenal.com/details/1/7818"><img src="https://img.shields.io/badge/Android%20Arsenal-Maildroid-green.svg?style=flat-square" border="0" alt="Android Arsenal"></a>	
</p>
<br>
<p align="center">

<img alt="JitPack" src="https://img.shields.io/jitpack/v/github/nedimf/maildroid?color=%230000&style=flat-square">
<a href="https://www.codacy.com/app/nedx45/maildroid?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=nedimf/maildroid&amp;utm_campaign=Badge_Grade"><img src="https://api.codacy.com/project/badge/Grade/0e4b1eea545649cbbc459d0a54bf64af"/></a>
 <a href="https://www.reddit.com/r/androiddev/comments/cotfeb/maildroid_new_email_library/"><img alt="Reddit" src="https://img.shields.io/badge/Reddit-androiddev-orange"></a>
 <img alt="Twitter Follow" src="https://img.shields.io/twitter/follow/_nedimf?color=%23&label=Follow&style=social">
	
	
</p>

**Comment by nedimf** [comment]
https://jitpack.io/#nedimf/maildroid , it's active.

**Comment by Jeluchu** [comment]
I have already found the error!

**Before**
`implementation 'com.github.nedimf:maildroid:v0.0.3'`

**After**
`implementation 'com.github.nedimf:maildroid:v.0.0.4'`

If you look you not only changed the version number, you also added a dot after the v

**v0.0.3 -> v.0.0.4**

That's why Android Studio couldn't find dependency, now if it works for me and you have taken it, thank you very much for the help received, and also thank you for your work since it is great

**Comment by nedimf** [comment]
Oh damn, I haven't noticed it, but I was sure that was something in that string.

**Comment by nedimf** [comment]
I have updated that to be v.0.0.4
