### ISSUE TITLE
 how to send mail to multiple users?

### ISSUE THREAD

**Issue by raul1525** [nedimf/maildroid#27]
Hello 
Could you support me or I would like to know if the email can be sent to multiple users.

Greetings

**Comment by nedimf** [comment]
Try `.to("email1@email.com, email2@email.com`. 

If this doesn't work, then library does not have that option, but can be certainly added. 

Waiting for you feedback.

**Comment by nedimf** [comment]
Close due to inactive response. Be free to reopen.
