### ISSUE TITLE
STARTTLS support?

### ISSUE THREAD

**Issue by Lars-** [nedimf/maildroid#30]
**Is your feature request related to a problem? Please describe.**
I would like to send mails via Office365, but I can't seem to find any documentation on STARTTLS.

**Describe the solution you'd like**
STARTTLS support or the documentation for it.

**Describe alternatives you've considered**
Nothing yet, MailDroid is already implemented, so it would be great to keep using it.

**Additional context**
None

**Comment by nedimf** [comment]
Sure, I'll add it by end of this week. Happy holidays @Lars-

**Comment by nedimf** [comment]
Hey @Lars- , checkout latest commit for the feature you requested, let me know if it works.

**Comment by Lars-** [comment]
Unfortunately, it doesn't work:
```
E/MessagingException: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.office365.com, 587; timeout -1;
      nested exception is:
    	java.net.SocketTimeoutException: failed to connect to smtp.office365.com/2603:1026:c03:3030::2 (port 587) after 90000ms
```

The code that I use:
```java
MaildroidX.Builder maildroidX = new MaildroidX.Builder()
                    .smtp(mailServer)
                    .smtpUsername(mailUser)
                    .smtpPassword(mailPassword)
                    .isStartTLSEnabled(true)
                    .port(String.valueOf(mailPort))
                    .type(MaildroidXType.PLAIN)

                    .to("[REDACTED]")
                    .from("[REDACTED]")
                    .subject("[REDACTED]")
                    .body(body)
                    .onCompleteCallback(new MaildroidX.onCompleteCallback() {
                        @Override
                        public void onSuccess() {
                         // Stuff
                        }

                        @Override
                        public void onFail(String s) {
                            //Stuff
                        }

                        @Override
                        public long getTimeout() {
                            return 5000;
                        }
                    });
```

When I try it with PHP, it does work. I looked it over a couple of times, but there doesn't seem to be any spelling mistake.
PHP code (using PHPMailer)
```php
        $mail->SMTPDebug = SMTP::DEBUG_OFF;
	$mail->isSMTP();
	$mail->Host       = 'smtp.office365.com';
	$mail->SMTPAuth   = true;
	$mail->Username   = '[REDACTED]';
	$mail->Password   = '[REDACTED]';
	$mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
	$mail->Port       = 587;

	$mail->setFrom( '[REDACTED]' );
	$mail->addAddress( '[REDACTED]' );

	foreach ( $files as $file ) {
		$mail->addAttachment( $file );
	}

	$mail->isHTML( false );
	$mail->Subject = $_POST['subject'] ?? '';
	$mail->Body    = $_POST['body'] ?? '';

	$mail->send();
```

What could the problem possibly be?

**Comment by nedimf** [comment]
Taking closer look at it, sorry for inconvenience

**Comment by Lars-** [comment]
I appreciate it, thanks! Maybe reopen the issue until it works?

**Comment by nedimf** [comment]
https://stackoverflow.com/a/58856313/11555781

**Comment by Lars-** [comment]
Yep, I checked it. The android app runs on the same network as the PHP script. So that couldn't be the problem.
The only thing that could be it is the verification of the certificate of office365. Maybe that version of Android doesn't know that certificate yet or something like that. Could be tested with a "do not verify certificate" option. I know that isn't safe, but it could explain it.

**Comment by nedimf** [comment]
Alright, what version of Android is that? @Lars-

**Comment by nedimf** [comment]
Is issue being resolved? @Lars-

**Comment by Lars-** [comment]
Sorry, missed your comment. It's running on Android 5.1 and unfortunately not upgradeable.

**Comment by nedimf** [comment]
I'm pretty sure issue is with 5.1 version it self. So library wise I don't see what can be done. SSL seems to work on other versions. @Lars-

**Comment by nedimf** [comment]
Concluding this is not Maildroid issue. This issue has been addressed.
