### ISSUE TITLE
attachment

### ISSUE THREAD

**Issue by ragabhesham3** [nedimf/maildroid#35]
i'm using this code for getting asking user to choose which file he wants to upload 
but i cannot know the way for getting the correct path from Uri to put it in .attachment
can you told me how?
i need you to explain a way to put Uri in attachment when get it from onActivityResult put it in new     fun sendEmail() {
}
it's kotlin code

```
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        if (requestCode == PICK_FROM_GALLERY && resultCode == RESULT_OK) {
            imageUri = data?.data!!
        }
    }

    private fun openFilePicker() {
        val i = Intent(
            Intent.ACTION_PICK,
            MediaStore.Images.Media.EXTERNAL_CONTENT_URI
        )
        i.type = "image/*"
        i.putExtra("return-data", true)

        startActivityForResult(i, PICK_FROM_GALLERY)
    }
```

**Comment by nedimf** [comment]
Hi, @ragabhesham3. Even tho this is not a valid question for this library I can try to help you with answering it.
```kotlin
var pictureUri = Uri.fromFile(pictureFile);
```
You can try that block of code. I'll be closing this issue and I'm gonna reference it to [StackOverflow](https://stackoverflow.com/questions/7241106/send-an-image-from-url-as-a-attachment-email-in-android) in hope it will help someone else in future.
