### ISSUE TITLE
Error in compilation

### ISSUE THREAD

**Issue by miguelmanas93** [nedimf/maildroid#36]
Since today, for no reason, the library has stopped working and it always gives me an error, I have spent hours with the project to see what was failing until I finally discovered that it was this ... check it

/.gradle/caches/transforms-2/files-2.1/73a03b94eee9f632e5fc0cdc50cafb02/jetified-kotlin-stdlib-1.5.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.

**Comment by nedimf** [comment]
According to this [StackOverflow post](https://stackoverflow.com/a/67470309)this is not problem with library. Issue is in `Gradle` it self.

Try upgrading `Gradle`.

I'll be closing this issue because it's not related to library it self.

**Comment by miguelmanas93** [comment]
It is completely related to the library, if I deactivate the library, the project compiles, if I activate it, it does not compile and gives an error. Therefore what fails is the module of this library when inserting it in the gradle. Everything is up to date

**Comment by nedimf** [comment]
@miguelmanas93 did you try increasing ``ext.kotlin.version`` to latest ``1.43.2``, referencing [this](https://stackoverflow.com/a/67816693/11555781)

**Comment by miguelmanas93** [comment]
> @miguelmanas93 did you try increasing `ext.kotlin.version` to latest `1.43.2`, referencing [this](https://stackoverflow.com/a/67816693/11555781)

Not work this

**Solution**
Finally, I downloaded the library and inserted the module myself, you have to change the gradle of the module as follows

change this: implementation "androidx.core:core-ktx:+"

by implementation "androidx.core:core-ktx:1.5.0"
