### ISSUE TITLE
The "from" field should be able to support the name, along with the email address.

### ISSUE THREAD

**Issue by Hsn37** [nedimf/maildroid#40]
**Is your feature request related to a problem? Please describe.**
Currently, the "from" field only takes in the email address. When the email is received, the name of the sender is thus shown as the prefix of the email, and not the actual username.

**Describe the solution you'd like**
`message.setFrom(InternetAddress(from))
InternetAddress can take 2 arguments, where the first one is the email, and the second is the username.

Have to simply add another field for the username.

**Comment by nedimf** [comment]
Hi, Maildroid uses different approach with sending emails and that approach is fully consistent with JavaMail APIs.
So at this time I won't be adding this feature, and I'll be closing this issue, if further interest appears be free to reopen this.
