### ISSUE TITLE
Mailing not working with a list of 1 email

### ISSUE THREAD

**Issue by adrixgc** [nedimf/maildroid#46]
**Describe the bug**
When sending an email with either to/cc/bcc with a list of only 1 email, it doesn't send it.

**To Reproduce**
1. Send an email using either fields to/cc/bcc with a list containing only 1 email. It should send it, but it checks that the list size is > 1, which is false. I expect it to work since you can select emails from a list, and the result could be 1 or many selected emails, and having to control if the selected values are 1 or many is a nightmare.

**Comment by nedimf** [comment]
Fixed with #47. Closing this issue.
