### ISSUE TITLE
MessagingException: IOException while sending message; .... no object DCH for MIME type multipart/mixed;

### ISSUE THREAD

**Issue by mengbai123** [nedimf/maildroid#49]
My app is perfectly fine in general, but I need to use apktools to modify and repackage it into some different version, and I get errors on the new app.

Bug occurs in Transport.send() function

![Snipaste_2023-05-17_15-15-58](https://github.com/nedimf/maildroid/assets/46396635/70333a9e-47d0-4ed3-a363-52fbf9b25566)
![Snipaste_2023-05-17_15-15-51](https://github.com/nedimf/maildroid/assets/46396635/2798d27f-ef36-48a4-a784-097100278640)

Here are some bug related pages I found

https://www.e-learn.cn/qa/q-218039.html

I found a solution based on the page above
Add such code to `Builder` class it will allright

```kotlin
open class Builder {

        init {
            (CommandMap.getDefaultCommandMap() as MailcapCommandMap).apply {
                addMailcap("text/html;; x-java-content-handler=com.sun.mail.handlers.text_html")
                addMailcap("text/xml;; x-java-content-handler=com.sun.mail.handlers.text_xml")
                addMailcap("text/plain;; x-java-content-handler=com.sun.mail.handlers.text_plain")
                addMailcap("multipart/*;; x-java-content-handler=com.sun.mail.handlers.multipart_mixed")
                addMailcap("message/rfc822;; x-java-content- handler=com.sun.mail.handlers.message_rfc822")
            }
        }

```

**Comment by nedimf** [comment]
Be free to add PR, if you think this could solve it.

**Comment by KamilK2003** [comment]
Hi, is there ultimately something I could do to avoid this bug?
@mengbai123 
@nedimf 

Regards, Kamil

**Comment by nedimf** [comment]
Sorry for a late, answer but it seems that this bug happens only if you are repackaging app.
