### ISSUE TITLE
[BUG] Sample app crashes if some fields are omitted when building the email.

### ISSUE THREAD

**Issue by javier-moreno** [nedimf/maildroid#6]
**Describe the bug**
If fields are omitted when using the `Builder` the app will crash or behave improperly when running the code because null checks are not done properly.

**To Reproduce**
1. omit calling `attachment(...)`
2. Run the app
3. Touch `SEND EMAIL`
4. App will crash

**Expected behavior**
App shouldn't crash and email should be sent without attachment

**Additional context**
Builder pattern should allow for omitting whatever and still work. They might be other fields that cause this behavior, didn't test all of them only attachment.

**Comment by nedimf** [comment]
That really should not happen, I will label it urgent
