### ISSUE TITLE
[Suggestion] Code Styling

### ISSUE THREAD

**Issue by javier-moreno** [nedimf/maildroid#7]
Current code has some styling issues and inconsistency that need to be fixed, for example:

1. Use of `;` in kotlin code
2. Irregular new lines between lines of code
3. Indentation issues in different part of the codes

The current source code lacks any design guidelines. This makes it hard when multiple people are collaborating since each developer has its own personal set of rules and styles guidelines. I'm avid user of [ktlint](https://github.com/pinterest/ktlint) for checking my code style. I'm willing to set it up in the code base and help maintain it.

**Comment by nedimf** [comment]
I agree  :+1:
